### ISSUE TITLE
Add a command to convert a `.yarn` file to a JSON export

### ISSUE THREAD

**Issue by weaversam8** [YarnSpinnerTool/YarnSpinner-Console#5]
If I'm setting up a CI workflow for Yarn files, I'd love to be able to convert a `.yarn` file to a `.json` file similar to how YarnEditor allows users to export those.

**Comment by McJones** [comment]
Due to the current structure of Yarn v2 files being essentially incompatible with the older json structure an exporter wouldn't realistically be possible, or would more accurately be more work than we feel its worth doing.

We personally feel the correct approach is to be moving away from v1 Yarn into the newer Yarn formats
If you want to make a PR that does this however we will happily take a look at that, but at this stage we feel its out of scope for the project.
